import {
  generateAugmentTypeYaml,
  generateCrucibleItemYaml,
  generateEquipmentSetYaml,
} from '../../mythiccrucible/generators'
import type { FileRecord } from '../../../types'
import { exampleFile, packBase } from './helpers'

export function buildGaleboundCrucibleFiles(packName: string): FileRecord[] {
  const base = packBase(packName)

  const equipmentSet = generateEquipmentSetYaml({
    id: 'Galebound_Regalia',
    display: '<aqua>Galebound Regalia',
    enabled: true,
    lore:
      '<yellow>[2]: <gray>+8 Defense\n<yellow>[4]: <gray>Chance to retaliate with static',
    bonuses: [
      { pieces: 2, stats: 'DEFENSE 8 ADDITIVE', skills: '' },
      {
        pieces: 4,
        stats: 'CRITICAL_STRIKE_DAMAGE 0.08 ADDITIVE',
        skills: 'skill{s=Galebound_SetStatic} @trigger ~onDamaged 0.25',
      },
    ],
  })

  const augmentType = generateAugmentTypeYaml({
    id: 'STATIC_RUNE',
    display: 'Static Rune',
    enabled: true,
    emptyFormat: '<augment.icon> Empty <augment.type> Slot',
    filledFormat: '<augment.icon> <augment.type>: <augment.tooltip>',
    showEmptySlot: true,
    iconEmpty: '◇',
    iconFilled: '◆',
    iconInvalid: '✗',
  })

  const arcblade = generateCrucibleItemYaml({
    id: 'Galebound_Arcblade',
    material: 'IRON_SWORD',
    display: '<aqua>Galebound Arcblade',
    group: 'weapons',
    itemKind: 'ITEM',
    role: 'standard',
    lore: '{stats}\n{stats}<gray>Stats:\n{stats-each}<white><stat.display>',
    loreTemplate: '',
    stats: 'ATTACK_DAMAGE 7 ADDITIVE\nCRITICAL_STRIKE_CHANCE 0.04 ADDITIVE',
    equipmentSet: '',
    skills: 'ignite{t=40} @target ~onHit',
    optionsCancelDamage: false,
    optionsKeepOnDeath: false,
    optionsPreventDropping: false,
    optionsPlaceable: true,
    optionsPreventEnchanting: false,
    optionsPreventStacking: false,
    optionsRepairable: true,
    itemUpdaterVersion: 0,
    maxDurability: '',
    durability: '',
    defaultLevel: '',
    maxLevel: '',
    augmentSlotType: '',
    augmentSlotAmount: '1',
    augmentSlotChance: '1',
    augmentSlotMaxAmount: '',
    augmentType: '',
    augmentTooltip: '',
    augmentRemoverDestroySocket: false,
    augmentRemoverReturnAugment: true,
    augmentSocketMaxSockets: 1,
    bagSize: 9,
    bagTitle: '',
    bagPreventNesting: true,
    bagSaveOnUpdate: true,
    bagAutoPickup: false,
    recipeType: '',
    recipeIngredients: '',
  })

  const helm = generateCrucibleItemYaml({
    id: 'Galebound_Regalia_Helm',
    material: 'IRON_HELMET',
    display: '<aqua>Galebound Regalia Helm',
    group: 'galebound_regalia',
    itemKind: 'ITEM',
    role: 'standard',
    lore: '{stats}\n{stats}<gray>Stats:\n{stats-each}<white><stat.display>\n{equipment-set}',
    loreTemplate: '',
    stats: 'DEFENSE 4 ADDITIVE',
    equipmentSet: 'Galebound_Regalia',
    skills: '',
    optionsCancelDamage: false,
    optionsKeepOnDeath: false,
    optionsPreventDropping: false,
    optionsPlaceable: true,
    optionsPreventEnchanting: false,
    optionsPreventStacking: false,
    optionsRepairable: true,
    itemUpdaterVersion: 0,
    maxDurability: '',
    durability: '',
    defaultLevel: '',
    maxLevel: '',
    augmentSlotType: 'STATIC_RUNE',
    augmentSlotAmount: '1',
    augmentSlotChance: '1',
    augmentSlotMaxAmount: '',
    augmentType: '',
    augmentTooltip: '',
    augmentRemoverDestroySocket: false,
    augmentRemoverReturnAugment: true,
    augmentSocketMaxSockets: 1,
    bagSize: 9,
    bagTitle: '',
    bagPreventNesting: true,
    bagSaveOnUpdate: true,
    bagAutoPickup: false,
    recipeType: '',
    recipeIngredients: '',
  })

  const runeShard = generateCrucibleItemYaml({
    id: 'Static_Rune_Shard',
    material: 'AMETHYST_SHARD',
    display: '<aqua>Static Rune Shard',
    group: 'gems',
    itemKind: 'ITEM',
    role: 'gem',
    lore: '',
    loreTemplate: '',
    stats: 'ATTACK_SPEED 0.08 ADDITIVE',
    equipmentSet: '',
    skills: '',
    optionsCancelDamage: false,
    optionsKeepOnDeath: false,
    optionsPreventDropping: false,
    optionsPlaceable: false,
    optionsPreventEnchanting: false,
    optionsPreventStacking: false,
    optionsRepairable: true,
    itemUpdaterVersion: 0,
    maxDurability: '',
    durability: '',
    defaultLevel: '',
    maxLevel: '',
    augmentSlotType: '',
    augmentSlotAmount: '1',
    augmentSlotChance: '1',
    augmentSlotMaxAmount: '',
    augmentType: 'STATIC_RUNE',
    augmentTooltip: '<aqua>+0.08 Attack Speed',
    augmentRemoverDestroySocket: false,
    augmentRemoverReturnAugment: true,
    augmentSocketMaxSockets: 1,
    bagSize: 9,
    bagTitle: '',
    bagPreventNesting: true,
    bagSaveOnUpdate: true,
    bagAutoPickup: false,
    recipeType: '',
    recipeIngredients: '',
  })

  const tonic = generateCrucibleItemYaml({
    id: 'Galebound_Tonic',
    material: 'POTION',
    display: '<b>Galebound Tonic',
    group: 'consumables',
    itemKind: 'ITEM',
    role: 'standard',
    lore: '<gray>Right-click to recover health.',
    loreTemplate: '',
    stats: '',
    equipmentSet: '',
    skills:
      'skill{s=[\n  - potion{type=REGEN;duration=80;level=1}\n  - heal{a=4}\n  - consumeuseditem{amount=1} @self\n]} @self ~onUse',
    optionsCancelDamage: false,
    optionsKeepOnDeath: false,
    optionsPreventDropping: false,
    optionsPlaceable: false,
    optionsPreventEnchanting: false,
    optionsPreventStacking: false,
    optionsRepairable: true,
    itemUpdaterVersion: 0,
    maxDurability: '',
    durability: '',
    defaultLevel: '',
    maxLevel: '',
    augmentSlotType: '',
    augmentSlotAmount: '1',
    augmentSlotChance: '1',
    augmentSlotMaxAmount: '',
    augmentType: '',
    augmentTooltip: '',
    augmentRemoverDestroySocket: false,
    augmentRemoverReturnAugment: true,
    augmentSocketMaxSockets: 1,
    bagSize: 9,
    bagTitle: '',
    bagPreventNesting: true,
    bagSaveOnUpdate: true,
    bagAutoPickup: false,
    recipeType: '',
    recipeIngredients: '',
  })

  return [
    exampleFile(
      `${base}/equipment-sets.yml`,
      `# Galebound Regalia — 4pc set bonus calls Galebound_SetStatic in Skills/galebound_storm.yml\n\n${equipmentSet.trim()}\n`,
      packName,
      'equipment-sets',
    ),
    exampleFile(
      `${base}/augments.yml`,
      `# Static Rune augment type — socketed on Galebound_Regalia_Helm\n\n${augmentType.trim()}\n`,
      packName,
      'augments',
    ),
    exampleFile(
      `${base}/Items/weapons.yml`,
      `# Crucible weapons\n\n${arcblade.trim()}\n`,
      packName,
      'items',
    ),
    exampleFile(
      `${base}/Items/gear.yml`,
      `# Set piece and augment gem — links equipment-sets.yml and augments.yml\n\n${helm.trim()}\n${runeShard.trim()}\n`,
      packName,
      'items',
    ),
    exampleFile(
      `${base}/Items/consumables.yml`,
      `# Server-ready consumable\n\n${tonic.trim()}\n`,
      packName,
      'items',
    ),
  ]
}
